//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.26 at 05:49:30 PM CEST 
//


package org.emau.icmvc.ganimed.deduplication.config.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchingConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchingConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="report-file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deduplication-algorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preprocessing-config" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}PreprocessingConfig" minOccurs="0"/>
 *         &lt;element name="required-config" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}RequiredConfig" minOccurs="0"/>
 *         &lt;element name="object-of-single-truth" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}ObjectOfSingleTruth"/>
 *         &lt;element name="blocking" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}Blocking"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchingConfiguration", propOrder = {
    "version",
    "pageSize",
    "reportFile",
    "deduplicationAlgorithm",
    "preprocessingConfig",
    "requiredConfig",
    "objectOfSingleTruth",
    "blocking"
})
public class MatchingConfiguration {

    @XmlElement(required = true)
    protected String version;
    protected int pageSize;
    @XmlElement(name = "report-file", required = true)
    protected String reportFile;
    @XmlElement(name = "deduplication-algorithm", required = true)
    protected String deduplicationAlgorithm;
    @XmlElement(name = "preprocessing-config")
    protected PreprocessingConfig preprocessingConfig;
    @XmlElement(name = "required-config")
    protected RequiredConfig requiredConfig;
    @XmlElement(name = "object-of-single-truth", required = true)
    protected ObjectOfSingleTruth objectOfSingleTruth;
    @XmlElement(required = true)
    protected Blocking blocking;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     */
    public void setPageSize(int value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the reportFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFile() {
        return reportFile;
    }

    /**
     * Sets the value of the reportFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFile(String value) {
        this.reportFile = value;
    }

    /**
     * Gets the value of the deduplicationAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeduplicationAlgorithm() {
        return deduplicationAlgorithm;
    }

    /**
     * Sets the value of the deduplicationAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeduplicationAlgorithm(String value) {
        this.deduplicationAlgorithm = value;
    }

    /**
     * Gets the value of the preprocessingConfig property.
     * 
     * @return
     *     possible object is
     *     {@link PreprocessingConfig }
     *     
     */
    public PreprocessingConfig getPreprocessingConfig() {
        return preprocessingConfig;
    }

    /**
     * Sets the value of the preprocessingConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreprocessingConfig }
     *     
     */
    public void setPreprocessingConfig(PreprocessingConfig value) {
        this.preprocessingConfig = value;
    }

    /**
     * Gets the value of the requiredConfig property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredConfig }
     *     
     */
    public RequiredConfig getRequiredConfig() {
        return requiredConfig;
    }

    /**
     * Sets the value of the requiredConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredConfig }
     *     
     */
    public void setRequiredConfig(RequiredConfig value) {
        this.requiredConfig = value;
    }

    /**
     * Gets the value of the objectOfSingleTruth property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectOfSingleTruth }
     *     
     */
    public ObjectOfSingleTruth getObjectOfSingleTruth() {
        return objectOfSingleTruth;
    }

    /**
     * Sets the value of the objectOfSingleTruth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectOfSingleTruth }
     *     
     */
    public void setObjectOfSingleTruth(ObjectOfSingleTruth value) {
        this.objectOfSingleTruth = value;
    }

    /**
     * Gets the value of the blocking property.
     * 
     * @return
     *     possible object is
     *     {@link Blocking }
     *     
     */
    public Blocking getBlocking() {
        return blocking;
    }

    /**
     * Sets the value of the blocking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blocking }
     *     
     */
    public void setBlocking(Blocking value) {
        this.blocking = value;
    }

}
