//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.16 at 05:21:16 PM MESZ 
//

package org.emau.icmvc.ganimed.epix.common.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */


import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Patient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ganimed.icmvc.emau.org/common/model}Person">
 *       &lt;sequence>
 *         &lt;element name="cohort" type="{http://www.ganimed.icmvc.emau.org/common/model}Cohort"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient", namespace = "http://www.ganimed.icmvc.emau.org/common/model", propOrder = {"cohort"

})
public class Patient extends Person implements Serializable {

	private static final long serialVersionUID = -4853140507469010550L;

	protected Cohort cohort;

	public Patient() {
		super();
	}

	/**
	 * 
	 * @param firstName
	 * @param middleName
	 * @param lastName
	 * @param prefix
	 * @param suffix
	 * @param gender
	 * @param contact
	 * @param birthDate
	 * @param mpiid
	 * @param identifiers
	 * @param role
	 * @param birthPlace
	 * @param race
	 * @param religion
	 * @param mothersMaidenName
	 * @param degree
	 * @param motherTongue
	 * @param nationality
	 * @param civilStatus
	 * @param value1
	 * @param value2
	 * @param value3
	 * @param value4
	 * @param value5
	 * @param value6
	 * @param value7
	 * @param value8
	 * @param value9
	 * @param value10
	 */
	public Patient(String firstName, String middleName, String lastName, String prefix, String suffix, Gender gender,
			List<Contact> contact, Date birthDate, MPIID mpiid, List<Identifier> identifiers,
			PersonRole role, String birthPlace, String race, String religion, String mothersMaidenName, String degree,
			String motherTongue, String nationality, String civilStatus, Date originDate,
			String value1, String value2, String value3, String value4,	String value5, String value6, String value7,
			String value8, String value9, String value10) {
		super(firstName, middleName, lastName, prefix, suffix, gender, contact, birthDate, mpiid, identifiers, role,
				birthPlace, race, religion, mothersMaidenName, degree, motherTongue, nationality, civilStatus,
				originDate, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10);
	}
	
	   /**
     * Gets the value of the cohort property.
     * 
     * @return
     *     possible object is
     *     {@link Cohort }
     *     
     */
    public Cohort getCohort() {
        return cohort;
    }

    /**
     * Sets the value of the cohort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cohort }
     *     
     */
    public void setCohort(Cohort value) {
        this.cohort = value;
    }

	@Override
	public String toString() {
		return "Patient [birthPlace=" + birthPlace + ", race=" + race + ", religion=" + religion + ", mothersMaidenName=" + mothersMaidenName + ", id=" + id + ", firstName=" + firstName
				+ ", middleName=" + middleName + ", lastName=" + lastName + ", prefix=" + prefix + ", suffix=" + suffix + ", gender=" + gender + ", contact=" + contacts + ", birthDate=" + birthDate
				+ ", mpiid=" + mpiid + ", identifiers=" + identifiers +  "]";
	}

}
