//
/**
 * Copyright (C)
 * 
 * E-PIX von 
 * Universitätsmedizin Greifswald
 * Institut für Community Medicine
 * Abt. Versorgungsepidemiologie & Community Health
 * Christian Schack, Dirk Langner, Gregor Kötzschke
 * steht unter einer Creative Commons Namensnennung 
 * - Nicht-kommerziell - 
 * Weitergabe unter gleichen Bedingungen 3.0 Unported Lizenz.
 * Siehe http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:01:49 AM MESZ 
//

package org.emau.icmvc.ganimed.epix.common.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for QueryResponseEntry complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="QueryResponseEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" type="{http://www.ganimed.icmvc.emau.org/common/model}Person" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryResponseEntry", propOrder = { "personIdentities", "firstMpi", "localIdentifiers" })
public class QueryResponseEntry extends ResponseEntry implements Serializable {

	public QueryResponseEntry(ErrorCode errorCode, Person person, List<LinkedPerson> linkedPersons,
			List<Person> personIdentities) {
		super(errorCode, person, linkedPersons);
		this.personIdentities = personIdentities;
	}

	public QueryResponseEntry() {
		super();
	}

	private static final long serialVersionUID = 1667832880169177206L;

	@XmlElement(name = "person-identities", required = false)
	protected List<Person> personIdentities;

	private Identifier firstMpi;

	private List<Identifier> localIdentifiers;

	/**
	 * Gets the value of the personIdentities property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the personIdentities property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPersonIdentities().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Person }
	 * 
	 * 
	 */
	public List<Person> getPersonIdentities() {
		if (personIdentities == null) {
			personIdentities = new ArrayList<Person>();
		}
		return this.personIdentities;
	}

	public boolean isSetPersonIdentities() {
		return ((this.personIdentities != null) && (!this.personIdentities.isEmpty()));
	}

	public void unsetPersonIdentities() {
		this.personIdentities = null;
	}

	public Identifier getFirstMpi() {
		return firstMpi;
	}

	public void setFirstMpi(Identifier firstMpi) {
		this.firstMpi = firstMpi;
	}

	public List<Identifier> getLocalIdentifiers() {
		return localIdentifiers;
	}

	public void setLocalIdentifiers(List<Identifier> localIdentifiers) {
		this.localIdentifiers = localIdentifiers;
	}

	@Override
	public String toString() {
		return "QueryResponseEntry [personIdentities=" + personIdentities + ", firstMpi=" + firstMpi
				+ ", localIdentifiers=" + localIdentifiers + ", id=" + id + ", errorCode=" + errorCode + ", person="
				+ person + ", linkedPersons=" + linkedPersons + "]";
	}
}
