//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.22 at 11:28:30 AM MESZ 
//


package org.emau.icmvc.ganimed.epix.common.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.emau.icmvc.ganimed.epix.common.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Patient_QNAME = new QName("http://www.ganimed.icmvc.emau.org/common/model", "patient");
    private final static QName _Person_QNAME = new QName("http://www.ganimed.icmvc.emau.org/common/model", "person");
    private final static QName _MPIRequest_QNAME = new QName("http://www.ganimed.icmvc.emau.org/epix/common/model", "MPIRequest");
    private final static QName _HealthcareProvider_QNAME = new QName("http://www.ganimed.icmvc.emau.org/common/model", "healthcare-provider");
    private final static QName _MPIResponse_QNAME = new QName("http://www.ganimed.icmvc.emau.org/epix/common/model", "MPIResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.emau.icmvc.ganimed.epix.common.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MPIResponse }
     * 
     */
    public MPIResponse createMPIResponse() {
        return new MPIResponse();
    }

    /**
     * Create an instance of {@link MPIRequest }
     * 
     */
    public MPIRequest createMPIRequest() {
        return new MPIRequest();
    }

    /**
     * Create an instance of {@link ResponseEntry }
     * 
     */
    public ResponseEntry createResponseEntry() {
        return new ResponseEntry();
    }

    /**
     * Create an instance of {@link ErrorCode }
     * 
     */
    public ErrorCode createErrorCode() {
        return new ErrorCode();
    }

    /**
     * Create an instance of {@link LinkedPerson }
     * 
     */
    public LinkedPerson createLinkedPerson() {
        return new LinkedPerson();
    }

    /**
     * Create an instance of {@link RequestEntry }
     * 
     */
    public RequestEntry createRequestEntry() {
        return new RequestEntry();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link HealthcareProvider }
     * 
     */
    public HealthcareProvider createHealthcareProvider() {
        return new HealthcareProvider();
    }

    /**
     * Create an instance of {@link IdentifierDomain }
     * 
     */
    public IdentifierDomain createIdentifierDomain() {
        return new IdentifierDomain();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link MPIID }
     * 
     */
    public MPIID createMPIID() {
        return new MPIID();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link PersonRole }
     * 
     */
    public PersonRole createPersonRole() {
        return new PersonRole();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Patient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ganimed.icmvc.emau.org/common/model", name = "patient")
    public JAXBElement<Patient> createPatient(Patient value) {
        return new JAXBElement<Patient>(_Patient_QNAME, Patient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ganimed.icmvc.emau.org/common/model", name = "person")
    public JAXBElement<Person> createPerson(Person value) {
        return new JAXBElement<Person>(_Person_QNAME, Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MPIRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ganimed.icmvc.emau.org/epix/common/model", name = "MPIRequest")
    public JAXBElement<MPIRequest> createMPIRequest(MPIRequest value) {
        return new JAXBElement<MPIRequest>(_MPIRequest_QNAME, MPIRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HealthcareProvider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ganimed.icmvc.emau.org/common/model", name = "healthcare-provider")
    public JAXBElement<HealthcareProvider> createHealthcareProvider(HealthcareProvider value) {
        return new JAXBElement<HealthcareProvider>(_HealthcareProvider_QNAME, HealthcareProvider.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MPIResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ganimed.icmvc.emau.org/epix/common/model", name = "MPIResponse")
    public JAXBElement<MPIResponse> createMPIResponse(MPIResponse value) {
        return new JAXBElement<MPIResponse>(_MPIResponse_QNAME, MPIResponse.class, null, value);
    }

}
