//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.02 at 11:55:30 AM MESZ 
//


package org.emau.icmvc.ganimed.deduplication.config.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreprocessingField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreprocessingField">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="simple-transformation-type" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}Transformation" maxOccurs="unbounded"/>
 *           &lt;element name="complex-transformation-type" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}PreprocessingType"/>
 *           &lt;element name="list-transformation-type" type="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}PreprocessingType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreprocessingField", propOrder = {
    "fieldName",
    "simpleTransformationType",
    "complexTransformationType",
    "listTransformationType"
})
public class PreprocessingField {

    @XmlElement(name = "field-name", required = true)
    protected String fieldName;
    @XmlElement(name = "simple-transformation-type")
    protected List<Transformation> simpleTransformationType;
    @XmlElement(name = "complex-transformation-type")
    protected PreprocessingType complexTransformationType;
    @XmlElement(name = "list-transformation-type")
    protected PreprocessingType listTransformationType;

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldName(String value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the simpleTransformationType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simpleTransformationType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimpleTransformationType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transformation }
     * 
     * 
     */
    public List<Transformation> getSimpleTransformationType() {
        if (simpleTransformationType == null) {
            simpleTransformationType = new ArrayList<Transformation>();
        }
        return this.simpleTransformationType;
    }

    /**
     * Gets the value of the complexTransformationType property.
     * 
     * @return
     *     possible object is
     *     {@link PreprocessingType }
     *     
     */
    public PreprocessingType getComplexTransformationType() {
        return complexTransformationType;
    }

    /**
     * Sets the value of the complexTransformationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreprocessingType }
     *     
     */
    public void setComplexTransformationType(PreprocessingType value) {
        this.complexTransformationType = value;
    }

    /**
     * Gets the value of the listTransformationType property.
     * 
     * @return
     *     possible object is
     *     {@link PreprocessingType }
     *     
     */
    public PreprocessingType getListTransformationType() {
        return listTransformationType;
    }

    /**
     * Sets the value of the listTransformationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreprocessingType }
     *     
     */
    public void setListTransformationType(PreprocessingType value) {
        this.listTransformationType = value;
    }

}
