//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.26 at 05:49:30 PM CEST 
//


package org.emau.icmvc.ganimed.deduplication.config.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimpleTransformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleTransformation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ganimed.icmvc.emau.org/deduplication/config/model}Transformation">
 *       &lt;sequence>
 *         &lt;element name="input-pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="output-pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleTransformation", propOrder = {
    "inputPattern",
    "outputPattern"
})
public class SimpleTransformation
    extends Transformation
{

    @XmlElement(name = "input-pattern", required = true, defaultValue = "")
    protected String inputPattern;
    @XmlElement(name = "output-pattern", required = true, defaultValue = "")
    protected String outputPattern;

    /**
     * Gets the value of the inputPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputPattern() {
        return inputPattern;
    }

    /**
     * Sets the value of the inputPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputPattern(String value) {
        this.inputPattern = value;
    }

    /**
     * Gets the value of the outputPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputPattern() {
        return outputPattern;
    }

    /**
     * Sets the value of the outputPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputPattern(String value) {
        this.outputPattern = value;
    }

}
