//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.07 at 01:35:52 PM MESZ
//


package org.emau.icmvc.ganimed.epix.pdqquery.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchMask complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SearchMask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="first-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birth-day" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birth-month" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birth-year" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mpiid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identifier-domain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchMask", propOrder = {
    "firstName",
    "lastName",
    "birthDay",
    "birthMonth",
    "birthYear",
    "mpiid",
    "identifier",
    "identifierDomain",
    "and"
})
public class SearchMask
    implements Serializable
{

	private static final long serialVersionUID = 1541122266465986413L;
	@XmlElement(name = "first-name")
    protected String firstName;
    @XmlElement(name = "last-name")
    protected String lastName;
    @XmlElement(name = "birth-day")
    protected String birthDay;
    @XmlElement(name = "birth-month")
    protected String birthMonth;
    @XmlElement(name = "birth-year")
    protected String birthYear;
    protected String mpiid;
    protected String identifier;
    @XmlElement(name = "identifier-domain")
    protected String identifierDomain;
    @XmlElement(name = "and")
    protected boolean and;

    /**
     * Gets the value of the firstName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFirstName(String value) {
        firstName = value;
    }

    public boolean isSetFirstName() {
        return (firstName!= null);
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastName(String value) {
        lastName = value;
    }

    public boolean isSetLastName() {
        return (lastName!= null);
    }

    /**
     * Gets the value of the birthDay property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * Sets the value of the birthDay property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBirthDay(String value) {
        birthDay = value;
    }

    public boolean isSetBirthDay() {
        return (birthDay!= null);
    }

    /**
     * Gets the value of the birthMonth property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBirthMonth() {
        return birthMonth;
    }

    /**
     * Sets the value of the birthMonth property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBirthMonth(String value) {
        birthMonth = value;
    }

    public boolean isSetBirthMonth() {
        return (birthMonth!= null);
    }

    /**
     * Gets the value of the birthYear property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBirthYear() {
        return birthYear;
    }

    /**
     * Sets the value of the birthYear property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBirthYear(String value) {
        birthYear = value;
    }

    public boolean isSetBirthYear() {
        return (birthYear!= null);
    }

    /**
     * Gets the value of the mpiid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMpiid() {
        return mpiid;
    }

    /**
     * Sets the value of the mpiid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMpiid(String value) {
        mpiid = value;
    }

    public boolean isSetMpiid() {
        return (mpiid!= null);
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentifier(String value) {
        identifier = value;
    }

    public boolean isSetIdentifier() {
        return (identifier!= null);
    }

    /**
     * Gets the value of the identifierDomain property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdentifierDomain() {
        return identifierDomain;
    }

    /**
     * Sets the value of the identifierDomain property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdentifierDomain(String value) {
        identifierDomain = value;
    }

    public boolean isSetIdentifierDomain() {
        return (identifierDomain!= null);
    }

    /**
     * Sets the value for the AND Operation (true = AND; false = OR)
     *
     * @param value
     */
    public void setAnd(boolean value)
	{
		and = value;
	}

	public boolean isAnd()
	{
		return and;
	}
}
