//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.07 at 01:35:52 PM MESZ 
//


package org.emau.icmvc.ganimed.epix.pdqquery.model;

/*
 * ###license-information-start###
 * E-PIX - Enterprise Patient Identifier Cross-referencing
 * __
 * Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
 * 							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
 * 							concept and implementation
 * 							c. schack, d.langner, l. geidel
 * 							web client
 * 							a. blumentritt
 * 							g. weiher
 * 							please cite our publications
 * 							http://dx.doi.org/10.3414/ME14-01-0133
 * 							http://dx.doi.org/10.1186/s12967-015-0545-6
 * __
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * ###license-information-end###
 */

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.emau.icmvc.ganimed.epix.pdqquery.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EpixSearch_QNAME = new QName("http://www.ganimed.icmvc.emau.org/epix/pdqQuery/model", "epix-search");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.emau.icmvc.ganimed.epix.pdqquery.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchMask }
     * 
     */
    public SearchMask createSearchMask() {
        return new SearchMask();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchMask }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ganimed.icmvc.emau.org/epix/pdqQuery/model", name = "epix-search")
    public JAXBElement<SearchMask> createEpixSearch(SearchMask value) {
        return new JAXBElement<SearchMask>(_EpixSearch_QNAME, SearchMask.class, null, value);
    }

}
