<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.emau.icmvc.ttp.epix</groupId>
	<artifactId>epix-project</artifactId>
	<version>2024.3.0</version>

	<packaging>pom</packaging>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<ttp-web-common.version>2024.3.0</ttp-web-common.version>
		<project.shortName>epix</project.shortName>
		<project.upperName>EPIX</project.upperName>
		<display_version>${project.version}</display_version>
		<log4j.version>2.24.2</log4j.version>
		<ttp-noti.version>2024.1.1</ttp-noti.version>
		<ttp-gras.version>1.2.0</ttp-gras.version>
		<docker-shared-resources.version>2024.2.0</docker-shared-resources.version>
		<ths-utils.version>1.5.4</ths-utils.version>
		<excludeTests>Disabled,Integration,Selenium</excludeTests>
	</properties>

	<name>E-PIX</name>
	<url>https://www.ths-greifswald.de/epix</url>

	<modules>
		<module>epix-common</module>
		<module>epix-ejb</module>
		<module>epix-ear</module>
		<module>epix-web</module>
		<module>epix-coverage</module>
		<module>epix-docker</module>
	</modules>

	<profiles>
		<profile>
			<id>secured</id>
			<properties>
				<login.enable.start>--&gt;</login.enable.start>
				<login.enable.end>&lt;!--</login.enable.end>
				<gras-login.enable.start>--&gt;</gras-login.enable.start>
				<gras-login.enable.end>&lt;!--</gras-login.enable.end>
			</properties>
		</profile>
		<profile>
			<id>dev</id>
			<properties>
				<display_version>${project.version} - Build ${maven.build.timestamp} UTC</display_version>
				<maven.build.timestamp.format>yyyy-MM-dd HH:mm</maven.build.timestamp.format>
			</properties>
		</profile>
		<profile>
			<id>demo</id>
			<properties>
				<disclaimer.enable.start>--&gt;</disclaimer.enable.start>
				<disclaimer.enable.end>&lt;!--</disclaimer.enable.end>
				<display_version>${project.version} - Demo</display_version>
			</properties>
		</profile>
		<profile>
			<id>staticContext</id>
			<properties>
				<env.TTP_EPIX_WEB_CONTEXT>${project.shortName}-web</env.TTP_EPIX_WEB_CONTEXT>
				<env.TTP_EPIX_SOAP_CONTEXT>${project.shortName}</env.TTP_EPIX_SOAP_CONTEXT>
			</properties>
		</profile>
		<profile>
			<id>coverage</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>0.8.12</version>
						<executions>
							<execution>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
							</execution>
							<execution>
								<id>report</id>
								<phase>prepare-package</phase>
								<goals>
									<goal>report</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<!-- profiles for testing -->
		<profile>
			<id>integration</id>
			<properties>
				<excludeTests>Disabled</excludeTests>
			</properties>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-plugin</artifactId>
							<configuration>
								<groups>Integration</groups>
							</configuration>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
		<profile>
			<id>selenium</id>
			<properties>
				<excludeTests>Disabled</excludeTests>
			</properties>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-plugin</artifactId>
							<configuration>
								<groups>Selenium</groups>
							</configuration>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
	</profiles>

	<repositories>
		<repository>
			<id>ttp-releases</id>
			<name>Trusted Third Party Maven Repository</name>
			<url>https://nexus.icm.med.uni-greifswald.de/repository/maven-releases-extern</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<!-- E-PIX -->
			<dependency>
				<groupId>org.emau.icmvc.ttp.epix</groupId>
				<artifactId>epix-common</artifactId>
				<version>${project.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp.epix</groupId>
				<artifactId>epix-ejb</artifactId>
				<version>${project.version}</version>
				<type>ejb</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp.epix</groupId>
				<artifactId>epix-shared-resources</artifactId>
				<version>${project.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp.epix</groupId>
				<artifactId>epix-ear</artifactId>
				<version>${project.version}</version>
				<type>ear</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp.epix</groupId>
				<artifactId>epix-web</artifactId>
				<version>${project.version}</version>
				<type>war</type>
			</dependency>

			<!-- TTP utils and shared resources -->
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ths-utils</artifactId>
				<version>${ths-utils.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ttp-web-common</artifactId>
				<version>${ttp-web-common.version}</version>
				<type>war</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ttp-web-common</artifactId>
				<version>${ttp-web-common.version}</version>
				<classifier>classes</classifier>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>noti-shared-resources</artifactId>
				<version>${ttp-noti.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ths-notification-client-ear</artifactId>
				<version>${ttp-noti.version}</version>
				<type>ear</type>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ths-notification-service</artifactId>
				<version>${ttp-noti.version}</version>
				<type>war</type>
			</dependency>
			<dependency>
				<groupId>org.icmvc.ttp</groupId>
				<artifactId>gras-shared-resources</artifactId>
				<version>${ttp-gras.version}</version>
				<type>jar</type>
			</dependency>
			<dependency>
				<groupId>org.icmvc.ttp.docker</groupId>
				<artifactId>docker-shared-resources</artifactId>
				<version>${docker-shared-resources.version}</version>
				<type>jar</type>
			</dependency>

			<!-- Logging -->
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-api</artifactId>
				<version>${log4j.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>1.7.36</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-log4j12</artifactId>
				<version>2.0.16</version>
				<scope>provided</scope>
			</dependency>

			<!-- JavaEE APIs -->
			<dependency>
				<groupId>jakarta.platform</groupId>
				<artifactId>jakarta.jakartaee-api</artifactId>
				<version>10.0.0</version>
				<scope>provided</scope>
			</dependency>

			<!-- Apache Commons -->
			<dependency>
				<groupId>commons-codec</groupId>
				<artifactId>commons-codec</artifactId>
				<version>1.17.1</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-collections4</artifactId>
				<version>4.4</version>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>3.17.0</version>
			</dependency>

			<!-- Persistence -->
			<dependency>
				<groupId>org.eclipse.persistence</groupId>
				<artifactId>eclipselink</artifactId>
				<version>4.0.4</version>
				<scope>provided</scope>
				<exclusions>
					<exclusion>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-core</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.eclipse.persistence</groupId>
				<artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
				<version>4.0.4</version>
				<scope>provided</scope>
			</dependency>

			<!-- Web -->
			<dependency>
				<groupId>org.primefaces</groupId>
				<artifactId>primefaces</artifactId>
				<version>14.0.8</version>
				<scope>provided</scope>
				<classifier>jakarta</classifier>
			</dependency>
			<dependency>
				<groupId>software.xdev</groupId>
				<artifactId>chartjs-java-model</artifactId>
				<version>2.5.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.ibm.icu</groupId>
				<artifactId>icu4j</artifactId>
				<version>76.1</version>
			</dependency>

			<!-- Java 9+ Kompatibilität -->
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-rt</artifactId>
				<version>4.0.3</version>
				<type>pom</type>
				<exclusions>
					<exclusion>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-core</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<!-- Other -->
			<dependency>
				<groupId>it.unimi.dsi</groupId>
				<artifactId>fastutil</artifactId>
				<version>8.5.15</version>
			</dependency>
			<dependency>
				<groupId>com.wutka</groupId>
				<artifactId>dtdparser</artifactId>
				<version>1.21</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.jboss.ejb3</groupId>
				<artifactId>jboss-ejb3-ext-api</artifactId>
				<version>2.4.0.Final</version>
				<scope>provided</scope>
			</dependency>

			<!-- Tests -->
			<dependency>
				<groupId>ch.qos.logback</groupId>
				<artifactId>logback-core</artifactId>
				<version>1.5.12</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>ch.qos.logback</groupId>
				<artifactId>logback-classic</artifactId>
				<version>1.5.12</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>com.sun.faces</groupId>
				<artifactId>jsf-api</artifactId>
				<version>2.2.20</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>nl.jqno.equalsverifier</groupId>
				<artifactId>equalsverifier</artifactId>
				<version>3.17.4</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-frontend-jaxws</artifactId>
				<scope>test</scope>
				<version>4.0.5</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-transports-http-jetty</artifactId>
				<scope>test</scope>
				<version>4.0.5</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-core</artifactId>
				<version>${log4j.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.emau.icmvc.ttp</groupId>
				<artifactId>ttp-web-common</artifactId>
				<version>${ttp-web-common.version}</version>
				<type>test-jar</type>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
				<version>5.11.3</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>5.14.2</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.jqno.equalsverifier</groupId>
			<artifactId>equalsverifier</artifactId>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.4.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-ejb-plugin</artifactId>
					<version>3.2.1</version>
					<configuration>
						<ejbVersion>3.2</ejbVersion>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-ear-plugin</artifactId>
					<version>3.3.0</version>
					<configuration>
						<version>6</version>
						<filtering>true</filtering>
						<jboss>
							<version>5</version>
						</jboss>
						<defaultLibBundleDir>lib</defaultLibBundleDir>
						<applicationName>epix</applicationName>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
					<configuration>
						<source>21</source>
						<target>21</target>
						<debug>true</debug>
						<debuglevel>source,lines,vars</debuglevel>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>3.4.0</version>
					<configuration>
						<archive>
							<manifestEntries>
								<Dependencies>org.slf4j, deployment.epix-ear-${project.version}.ear</Dependencies>
							</manifestEntries>
						</archive>
						<nonFilteredFileExtensions>
							<nonFilteredFileExtension>gif</nonFilteredFileExtension>
							<nonFilteredFileExtension>ico</nonFilteredFileExtension>
							<nonFilteredFileExtension>jpg</nonFilteredFileExtension>
							<nonFilteredFileExtension>png</nonFilteredFileExtension>
							<nonFilteredFileExtension>pdf</nonFilteredFileExtension>
						</nonFilteredFileExtensions>
						<webResources>
							<resource>
								<directory>src/main/webapp</directory>
								<filtering>true</filtering>
							</resource>
						</webResources>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>3.1.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.22.2</version>
					<configuration>
						<excludedGroups>${excludeTests}</excludedGroups>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>3.4.1</version>
					<configuration>
						<windowtitle>E-PIX ${project.version} API</windowtitle>
						<bottom><![CDATA[E-PIX ${project.version} API, Copyright 2025, <a href="https://www.ths-greifswald.de">ths-greifswald.de<a>]]></bottom>
					</configuration>
				</plugin>
				<plugin>
					<!--To update license details:
					set canUpdateCopyright to true and run with maven goal 'license:update-file-header'
					set canUpdateCopyright to false before committing changes -->
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>license-maven-plugin</artifactId>
					<version>1.20</version>
					<configuration>
						<canUpdateCopyright>false</canUpdateCopyright>
						<verbose>false</verbose>
						<processStartTag>###license-information-start###</processStartTag>
						<processEndTag>###license-information-end###</processEndTag>
						<sectionDelimiter>__</sectionDelimiter>
						<projectName>E-PIX - Enterprise Identifier Cross-Referencing</projectName>
						<inceptionYear>2009</inceptionYear>
						<organizationName>Trusted Third Party of the University Medicine Greifswald
							kontakt-ths@uni-greifswald.de

							concept and implementation
							l.geidel,c.schack, d.langner, g.koetzschke

							web client
							a.blumentritt, f.m. moser

							docker
							r.schuldt, f.m. moser

							privacy preserving record linkage (PPRL)
							c.hampf

							please cite our publications
							http://dx.doi.org/10.3414/ME14-01-0133
							http://dx.doi.org/10.1186/s12967-015-0545-6
							https://translational-medicine.biomedcentral.com/articles/10.1186/s12967-020-02257-4
						</organizationName>
						<licenseName>agpl_v3</licenseName>
						<excludes>
							<exclude>**/beans.xml</exclude>
							<exclude>main/java/com/google/gwt/dev/util/editdistance/*.java</exclude>
							<exclude>**/*.json</exclude>
						</excludes>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
