version: '3.7'
services:

  wildfly:
    image: docker.icm.med.uni-greifswald.de/ths/docker/wildfly-db:${docker.wildfly.version}
    container_name: ${project.shortName}-wildfly-db
    ports:
      - "3306:3306"
#      - "8787:8787"
      - "8080:8080"
      - "9990:9990"
    env_file:
      - ./envs/mysql.env
      - ./envs/ttp_commons.env
      - ./envs/ttp_${project.shortName}.env
      - ./envs/wf_commons.env
    volumes:
      - ./jboss:${docker.wildfly.jboss}
      - ./deployments:${docker.wildfly.deployments}
      - ./logs:${docker.wildfly.logs}
      - ./sqls:${docker.wildfly.sqls}
#      - ./data/mysql:${docker.wildfly.dbdata}
  jmeter:
    image: mosaicgreifswald/jmeter:5
    container_name: ${project.shortName}-jmeter
    depends_on:
      - wildfly
    env_file:
      - ./envs/ttp_loadtest.env
    volumes:
      - ./jmeter:/entrypoint-jmeter-testfiles
      - ./logs/:/entrypoint-jmeter-logs
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh wildfly:9990 -t 400 && sleep 10 && ./run.sh"
